name: Build Check
on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  arch:
    name: Arch Linux
    runs-on: ubuntu-latest
    container: docker.io/library/archlinux:latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Update packages
        run: pacman -Syu --noconfirm
      - name: Install build dependencies
        run: pacman -S --noconfirm base-devel cmake ninja qt5-base qt5-tools dtkwidget appstream-qt5 packagekit-qt5
      - name: CMake and Make
        run: |
          mkdir build
          cd build
          cmake ../ -G Ninja
          ninja
  debian:
    name: Debian
    runs-on: debian-latest
    container: docker.io/library/debian:unstable
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Refresh repos
        run: apt-get update
      - name: Install build dependencies
        run: DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential cmake ninja-build pkg-config qtbase5-dev libdtkwidget-dev libdtkcore-dev libdtkgui-dev libpackagekitqt5-dev libappstreamqt5-dev (>= 1.0.0~) libsnapd-qt-dev qttools5-dev
      - name: CMake and Make
        run: |
          mkdir build
          cd build
          cmake ../ -G Ninja
          ninja
  ubuntudde:
    name: UbuntuDDE
    runs-on: ubuntu-latest
    container: docker.io/library/ubuntu:24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Refresh repos
        run: apt-get update
      - name: Add UbuntuDDE PPA
        run: |
          apt-get -y install software-properties-common
          add-apt-repository -y ppa:ubuntudde-dev/stable
          apt-get update
      - name: Install build dependencies
        run: DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential cmake ninja-build pkg-config qtbase5-dev libdtkwidget-dev libdtkcore-dev libdtkgui-dev libpackagekitqt5-dev libappstreamqt5-dev (>= 1.0.0~) libsnapd-qt-dev qttools5-dev
      - name: CMake and Make
        run: |
          mkdir build
          cd build
          cmake ../ -G Ninja
          ninja
